### PR TITLE
Quick pick selection of sketch files

### PR DESCRIPTION
**Pull request by maddogjt**
- Replace arduino.setSketchFile command with new arduino.selectSketch command which presents the user with a quick select containing all of the sketch files in the workspace.
- Add "Arduino: Select Sketch" to the command palette
- When picking sketches, filter out hardware, library, and build folders that may be under the workspace

### CODE REVIEW

**Comment by maddogjt** [comment]
@adiazulay saw that you're merging some pull requests.  I rebased this to the latest develop if you have a chance to take a look.

**Comment by adiazulay** [comment]
@maddogjt I'll review this PR for the next release

**Comment by anthonyptetlow** [comment]
@adiazulay Is ther any update on this getting reviewed, merged and released?

**Comment by adiazulay** [comment]
@anthonyptetlow I'll try to get this reviewed in the next week or 2.

**Review by adiazulay — APPROVED** [review]
Looks good to me

**Comment by anthonyptetlow** [comment]
Thanks guys really appreciate it :-D

**Pull request merged**
