### PR TITLE
Fix empty board and examples list

### LINKED ISSUE #1163: Cannot select board type
image
 Nothing is showing when i try to select the board type but i am able to select the serial port. I am able to use Arduino IDE to upload sketches though.

OS: Arch Linux

### LINKED ISSUE #1360: v0.4.6 board selection does not show any board
tried both on vscode 1.58 and 1.60.2

reverting back to v0.4.3 works, bur serial selection is not working with vscode 1.60.2

vscode 1.60.2 with arduino-vscode v0.4.5 works fine

System : windows 10 build 19043

### LINKED ISSUE #1361: Bug of vscode-arduino: no results found when selecting board
I have configured vscode-arduino extension as requested. I set "arduino.path" to "C:\Program Files (x86)\Arduino", and set "arduino.commandPath" to "arduino_debug.exe". But when I open blink.ino and click the <Select Board Type>, it says "No results found". I am pretty sure that my board (Arduino Uno) has been connected to my computer and I can upload my program through Arduino IDE. How can I fix the problem?

Snipaste_2021-09-30_15-27-32

Snipaste_2021-09-30_15-27-32

Arduino IDE version: 1.8.16
Arduino IDE installation path: C:\Program Files (x86)\Arduino
vscode version: 1.60.2
OS: windows 10

### LINKED ISSUE #1363: Cannot access the examples in latest update
- Press F1
- Select "Arduino: Examples"
- An empty tab appears on Linux

Downgrading fixed this issue.

### LINKED ISSUE #1372: Board manager isn't called properly in 0.4.6.
Hi,

Board list show no items when called. 0.4.5. works properly.

My config is the following:

Hardware

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro17,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	8 GB

OS MacOS BigSur 11.6 (20G165)

Arduino IDE 1.8.16

VS Code

1.61.1 (Universal)
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:23:30.274Z (5 days ago)
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

with plugins:
GitHub Pull Requests and Issues v0.31.0
C/C++ v1.7.0
Arduino as per above

Veiksmi,
Jānis

### PR DESCRIPTION
**Pull request by fredr**
This project is still running on react 15, and these `UNSAFE_*`-lifecycle aliases where not introduced until 16.3, hence they are never called.

fixes #1163, fixes #1360, fixes #1363, fixes #1361, fixes #1372

### CODE REVIEW

**Review by maddogjt — APPROVED** [review]
Tested this locally and it addresses the issues.

**Comment by julianrendell** [comment]
This is close to a showstopper for using VSCode + Arduino with new developers/students- especially if trying to import an existing project.

A partial workaround is to create a completely new folder, and then execute "Arduino-> initialize": this creates a new ino file and prompts for the board from the list of installed boards, and correctly generates the Arduino.json and c_cpp_properties files.

Is it possible to get an ETA on when this can be approved?

**Comment by GXTX** [comment]
Just a bump so org members see this.
What is the status? This change is required to actually use this extension unless you downgrade.

**Comment by benmcmorran** [comment]
Sorry about the delay everyone. I'm taking a look now.

**Comment by benmcmorran** [comment]
Looks like CI is broken (not your fault). I'm going to work on that in a separate PR, then come back and merge this.

**Review by benmcmorran — APPROVED** [review]

**Comment by benmcmorran** [comment]
I also had to make the change in #1379 to support the case where an `arduino.json` file is not already present. I'm building a new release candidate now and if everything looks good I'll push it out to the marketplace.

**Comment by fredr** [comment]
Awesome @benmcmorran, thank you!

**Comment by AlexIII** [comment]
It all works now, thank you!

**Pull request merged**
