### PR TITLE
Update node-usb-native dependency

### PR DESCRIPTION
**Pull request by robotdad**

### CODE REVIEW

**Review by maddogjt — APPROVED** [review]
Looks great, and essentially the same change I made in my fork to work around this.  Unfortunately I don't have submit access so don't know if my review is useful.

**Comment by robotdad** [comment]
Thanks @maddogjt, apologies for the slow going on our end here.

**Review by adiazulay — APPROVED** [review]
Looks good! thanks for doing this.

**Review by dilin-MS — APPROVED** [review]
Looks good to me!

**Pull request merged**
