### PR TITLE
Autogenerate c_cpp_properties.json

### LINKED ISSUE #438: The Extension should automagically fill the c_cpp_properties.json, so intellisense works out of the box
EDIT: 07/03/2018: My understanding of the issue has improved since I opened it. I think that the extension should fill the intellisense config file on the fly based on the board being selected by the user.

To my knowledge, the Arduino IDE checks for libraries in 4 places: the main Arduino installation path (in windows c:\program files.\...), any board-specific version of the libraries for this board ("...\appdata\local\..."), your sketchbook location and a "libraries" folder for that particular sketch. Ideally, you would install your libraries in your sketchbook location, so they are available for all your projects.

I've just installed VS Code and the Arduino plugin, and it seems to be able to know that my sketchbook location is not the default, as I can see the examples of the libraries that I've installed there, and I can compile my sketch. In any case, I get tens of intellisense errors, as intellisense seems incapable to follow the paths for the includes. I can add the sketchbook location libraries to the c_cpp_properties.json, and either add all the libraries used there (painfull) or add the base "libraries" folder and then tweak the includes to have partial paths (less painfull), but even in these cases, intellisense will complain that it can't find any of the libraries this files might use. And I would have to do it for all my projects, one by one.

What am I doing wrong? why doesn't this plugin pick the usual library locations? Is it normal to have 100s of intellisense errors? is that really the way it's meant to be?

Sorry, I'm new to Visual Studio and Visual Studio Code, and I'm quite sure that the problem it's me not being able to find out the logic behind them, but I can't find any info on the internet either.

I'm using windows 10 64 bits, and my arduino Ide is at the latest version. The relevant part of my  c_cpp_settings.json of this project is:

```{
            "name": "Win32",
            "includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/include/*",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/um",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/ucrt",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/shared",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/winrt",
                "${workspaceRoot}",
                "C:\\Users\\Joel\\AppData\\Local\\Arduino15\\packages\\SODAQ\\hardware\\samd\\1.6.14\\cores\\arduino"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/include/*",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/um",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/ucrt",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/shared",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.16299.0/winrt",
                    "${workspaceRoot}",
                    "C:\\Users\\Joel\\AppData\\Local\\Arduino15\\packages\\SODAQ\\hardware\\samd\\1.6.14\\cores\\arduino"
                ],
                "limitSymbolsToIncludedHeaders": false,
                "databaseFilename": ""
            }
        }
```

This is a screenshot of my project

### PR DESCRIPTION
**Pull request by iFreilicht**
Fixes #438, #808, #969

Potentially fixes other issues that stem from an incorrectly set up `c_cpp_properties.json`.

This PR adds an autogeneration mechanism to the extension. This way, library paths and macro definitions are added to `c_cpp_properties.json` automatically.

This fork is unfortunately a little older, so there may be some conflicts to fix, but I want to get it onto the radar, as it is a huge quality of life improvement and I've exclusively been using the development build of this fork because of that.

Builds of this fork of the extension can be found in [this dropbox folder](https://www.dropbox.com/sh/whmcdt26chyjgby/AAB1Ld2fzZ9Z_NfM3CRay17wa). Discussion around it is in #438 and this [gitter chatroom](https://gitter.im/vscode-arduino-ew-fork/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

Tagging @elektronikworkshop

### CODE REVIEW

**Comment by robotdad** [comment]
Is this ready for a review? If so I'll see if I can add it to the queue after we get the serial port issue resolved.

**Comment by iFreilicht** [comment]
For a general code review, yes, but it was built against an older version of the extension and there was no time to update it yet. Do you want to have a look anyway or should it merge the current master first?

**Comment by robotdad** [comment]
We'll discuss tomorrow morning here. Thank you for providing the PR, apologies it has sat here for so long.

**Comment by adiazulay** [comment]
@iFreilicht, can you rebase the current master branch on to this pr

**Comment by hlovdal** [comment]
Hi. I am not @iFreilicht, but I have rebased the branch on top of the latest master branch, see https://github.com/hlovdal/vscode-arduino/tree/intellisense-autoconfig.rebased. I have review each of the rebased commits to see that they looked valid and have compiled and tested with the resulting branch which generated a proper`.vscode/c_cpp_properties.json`.

**Comment by iFreilicht** [comment]
Thanks so much! I created a new PR with your branch, see #1141, and will close this one.

**Pull request closed without merging**
