### PR TITLE
Add Wio 3G board.

### PR DESCRIPTION
**Pull request by matsujirushi**

### CODE REVIEW

**Comment by Sneezry** [comment]
Thanks for the PR. Is there any information about this board? We cannot find it in seeed shop on taobao: https://seeedstudio.taobao.com/ or seeed official website: https://www.seeedstudio.com/series/Wio-11.html

**Comment by matsujirushi** [comment]
The board is distributed by SORACOM only.
https://soracom.jp/products/wio_3g_soracom_edition/

And we have plan that support Mbed OS.
https://os.mbed.com/platforms/Seeed-Wio-3G/

**Comment by Sneezry** [comment]
Sorry for late response. We are trying to buy this device online to verify this PR in these days. However, it seems hard to find in China. Could you please post some screenshots to show the verify result? Thanks.

**Comment by matsujirushi** [comment]
Oh...
Okay. Attached.
img_2235

**Comment by Sneezry** [comment]
Thanks for your contribution!

**Pull request merged**
