### PR TITLE
add sketch folder to examples

### PR DESCRIPTION
**Pull request by aster94**
solves #652 
screenshot 2018-09-07 15 25 29

video:
https://streamable.com/llhuc

@czgtest also said it would be a nice feature

### CODE REVIEW

**Comment by aster94** [comment]
Yes, i also made a video to show it in the first post

**Comment by aster94** [comment]
@czgtest you are right. Corrected

**Comment by czgtest** [comment]
@aster94   can you use the first letter lowercase for "Sketches"  in code ? 
path.join(this._settings.sketchbookPath, "Sketches");  

image

btw, if your folder named "Sketches" , it also can be opened in arduino example.

**Comment by aster94** [comment]
@czgtest done!

**Comment by czgtest** [comment]
Thank you a lot @aster94

**Pull request merged**
