### PR TITLE
Add OTA port discovery

### PR DESCRIPTION
**Pull request by BertvanHoekelen**
Add automatic OTA device discovery. 

Resolves issues:
https://github.com/Microsoft/vscode-arduino/issues/454
https://github.com/Microsoft/vscode-arduino/issues/452
https://github.com/Microsoft/vscode-arduino/issues/359

### CODE REVIEW

**Comment by esp13** [comment]
Hi,
I don't know what is to do, is there a way to get this nice feature to work?

Other question: in case of password use, how to send it? (In arduino.json, I tried "password": "xxx" and "auth": "xxx", neither of them are recognized)

**Comment by sobieh** [comment]
Are you guys going to merge this like ... ever ?

**Comment by OhMyGuus** [comment]
So yea RIP this PR it is sitting here since Nov 26, 2018. Would be nice if this would be merged at some point.

**Comment by BertvanHoekelen** [comment]
Yeah I stopped maintaining this PR because nobody reviewed or merged it. It's also a long time ago and don't have the answer for you @esp13 without looking it up.

**Comment by BertvanHoekelen** [comment]
Closing because lack of response.

**Comment by DennHa** [comment]
Would be great if this feature could me merged!

**Comment by hcooper** [comment]
+1 for actually getting this merged!

**Comment by BertvanHoekelen** [comment]
@hcooper don't get your hopes up. No response from mainteners so lost interest of keeping this PR alive.

**Pull request closed without merging**
