### PR TITLE
Don't use `*` activation event

### PR DESCRIPTION
**Pull request by BelKed**
Using the `*` activation event is not a best practise. Instead, it should use `onLanguage:cpp` or something similar.

I realized that in `onCommand:arduiono.cliUploadUsingProgrammer` is a typo so that's also fixed in this PR...

---

Related to
- https://github.com/microsoft/vscode-arduino/issues/1478

### CODE REVIEW

**Review by benmcmorran — APPROVED** [review]

**Comment by benmcmorran** [comment]
Thanks for the contribution @BelKed! Don't mind any comments I'm making below -- I'm just trying to convince the bot to run our private CI.

**Comment by daniel-stoneuk** [comment]
Just checking, would it be better to activate only on `**/*.ino`? I'm not super familiar with different types of arduino projects, so please correct me if I'm wrong!

**Comment by benmcmorran** [comment]
That's a good point. I was thinking that Arduino projects may include C/C++ sources in their projects, but you're right that there will always be at least one .ino file if it's an Arduino project. I'll create a follow-up PR with the change.

**Pull request merged**
