### PR TITLE
add default output path

### PR DESCRIPTION
**Pull request by aster94**
hello, this is a follow up from the pull request #623

i just modified the output path to work as global (i.e. defined once as the "arduino.path")
This way the user would need to choose it only once instead of choosing one for every sketch. This could be overwritten in the per sketch setting (i.e. .vscode/arduino.json)

i made a video to show that it works
https://streamable.com/casvh

### CODE REVIEW

**Comment by Sneezry** [comment]
Hi @aster94 , it seems this pr has code style issue. Please run tslint task to fix the issue.

**Comment by aster94** [comment]
@Sneezry done
before merging this could you give some suggestion on the desired output of this function?
https://github.com/aster94/vscode-arduino/blob/add-default-output-path/src/arduino/arduinoSettings.ts#L242 
i guess that the best would be `""` but i would rather to hear your opinion

**Comment by Sneezry** [comment]
@aster94 `null` or `undefined` makes more sense.

**Comment by aster94** [comment]
set as `undefined` let's wait for travis CI

**Comment by czgtest** [comment]
@aster94  Can you help to resolve conflicts?

**Comment by aster94** [comment]
@czgtest are you talking about merge conflicts? I don't see anymore any of them, you probably solved them with the last commit (fe2fc1c)
Anyway I remember that them were in the readMe file

**Comment by aster94** [comment]
Unfortunately i have been too busy in these days, i would do it during the holidaya

**Comment by aster94** [comment]
@czgtest the code works, the only problems i see are related to the trailing whitespaces, again
i already explained that it is nor related to my code but to the style i followed
i can remove these whitespaces if you really need to have tslint without errors. 
See the changes, test in your machine and decide yourself if you want to merge it or just close

here there is the output of  gulp tslint
[21:38:25] Using gulpfile ~/wip/git/vscode-arduino/gulpfile.js
[21:38:25] Starting 'tslint'...

/home/aster/wip/git/vscode-arduino/src/arduino/arduinoSettings.ts[39, 1]: trailing whitespace
/home/aster/wip/git/vscode-arduino/src/arduino/arduinoSettings.ts[160, 1]: trailing whitespace
/home/aster/wip/git/vscode-arduino/src/arduino/arduinoSettings.ts[238, 1]: trailing whitespace


/home/aster/wip/git/vscode-arduino/src/arduino/vscodeSettings.ts[81, 1]: trailing whitespace

[21:38:29] 'tslint' errored after 4.39 s
[21:38:29] Error in plugin 'gulp-tslint'
Message:
    Failed to lint: /home/aster/wip/git/vscode-arduino/src/arduino/arduinoSettings.ts [39, 1]: trailing whitespace, /home/aster/wip/git/vscode-arduino/src/arduino/arduinoSettings.ts [160, 1]: trailing whitespace, /home/aster/wip/git/vscode-arduino/src/arduino/arduinoSettings.ts [238, 1]: trailing whitespace, /home/aster/wip/git/vscode-arduino/src/arduino/vscodeSettings.ts [81, 1]: trailing whitespace.

**Comment by Sneezry** [comment]
@aster94 code works is basic requirement. If even the code doesn't work, the PR should not be made.

I find an answer on SO for you about why code style is important: https://stackoverflow.com/a/127955/2956469

This is not a personal project, and we will always adhere to the principle of code review.

**Comment by aster94** [comment]
This is completely no sense, i am saying that the tslint errors are due to the code style i followed and you say me that i didn t follow the code style

Again, as i wrote "i can remove these whitespaces if you really need to have tslint without errors." but this would bring to a mixed style (some function separate by a whytespace some are not)

I doubt that you ever saw the code changes 😂

**Comment by aster94** [comment]
> I wonder what code style you followed to leave these extra spaces.

Seriously? I really hope you are joking with me

> https://github.com/Microsoft/vscode-arduino/pull/655/files#diff-61a376a669275c4b558dffdd267a574dR39

let's have a look to https://github.com/Microsoft/vscode-arduino/blob/master/src/arduino/arduinoSettings.ts#L38 wow a whitespace! let's see who added it https://github.com/Microsoft/vscode-arduino/commit/c9876f94f3dfcf75b0156bc5db0da08bb6bddb3f#diff-61a376a669275c4b558dffdd267a574dR38 it's you with commit c9876f94f3dfcf75b0156bc5db0da08bb6bddb3f of the pull request https://github.com/Microsoft/vscode-arduino/pull/620

let's see another one: 

> https://github.com/Microsoft/vscode-arduino/pull/655/files#diff-61a376a669275c4b558dffdd267a574dR160

same whitespace: https://github.com/Microsoft/vscode-arduino/blob/master/src/arduino/arduinoSettings.ts#L156 try to guess who added it

do I need to continue?

> https://github.com/Microsoft/vscode-arduino/pull/655/files#diff-61a376a669275c4b558dffdd267a574dR39
>
> https://github.com/Microsoft/vscode-arduino/pull/655/files#diff-4df1b23848899e72d52d2f373f665a33R81

I know i am looking (too) sarcastic but before commenting and closing you could have given a better look to the code changes

**Comment by Sneezry** [comment]
> let's have a look to https://github.com/Microsoft/vscode-arduino/blob/master/src/arduino/arduinoSettings.ts#L38 wow a whitespace! let's see who added it c9876f9#diff-61a376a669275c4b558dffdd267a574dR38 it's you with commit c9876f9 of the pull request #620 

Compare with these two files:

https://raw.githubusercontent.com/Microsoft/vscode-arduino/master/src/arduino/arduinoSettings.ts

https://raw.githubusercontent.com/aster94/vscode-arduino/eed83d7e18836fd316e4aa5d18987c7dda7c6af4/src/arduino/arduinoSettings.ts

snipaste_2018-12-24_23-05-39

The rest are similar. I have no interest to argue with you, nor I have no time to do that.

**Comment by aster94** [comment]
you are right it's there i didn't saw it 😁

**Pull request closed without merging**
