### PR TITLE
Dynamically read programmers from platform

### PR DESCRIPTION
**Pull request by hairlesshobo**
Added support for reading programmers from the Arduino platforms' programmers.txt file. Also now the last used  for the project is reloaded upon project opening.

#578 
#898
#942

### CODE REVIEW

**Comment by tombarber** [comment]
This is just what I'm after, trying to use the "Pololu USB AVR Programmer" programmer for the 3pi.

**Comment by hairlesshobo** [comment]
Looks like this pull request went stale sitting for someone to approve it. I just updated the branch to the latest code and will wait to see if someone on the team will approve it now.

**Comment by PeterWone** [comment]
When there's no "last" selection and there's only one programmer detected it would be good to autoselect it.

**Comment by karintei** [comment]
Thanks to all of you for making a great improvement. The changes above, but unfortunately, don't seem to be merged into the current master branch.

**Comment by hairlesshobo** [comment]
Just wondering what it would take for this to be approved. I just verified that my code can still be merged without issue but it is still awaiting approval and has been for over a year. It would seem there are others who are also interested in this fix. 

Anyone able to help here?

**Comment by TheLinthus** [comment]
I was needing this solution. Would be nice to get it approved soon, as far I checked (manually installed) it work for the selection and upload.

**Comment by fennecbutt** [comment]
I could really use this bugfix as well, in the meantime I'm either going to have to bounce between Vscode & Arduino or manually run a script to flash with the correct programmer.

**Comment by Gurkengewuerz** [comment]
Any updates on this? Really need this!

**Comment by robotdad** [comment]
I'll see if I can get this into the review queue after we fix the serial port issue (soon).

**Comment by TamojitSaha** [comment]
Please merge this pull request as this would save us some time and ease the workflow in vs-code

**Comment by adiazulay** [comment]
I'm going to merge #1129 in early January and close out this PR. Both PRs populate the programmers list from programmers.txt files.

**Comment by adiazulay** [comment]
#1129 is merged to develop

**Pull request closed without merging**
