### PR TITLE
Support custom libraries with portable version of Arduino

### PR DESCRIPTION
**Pull request by raomin**
When running with a portable version of Adruino IDE, the custom libraries are put in: 
--> arduino-1.8.10\portable\sketchbook\libraries
(and not in Documents\Arduino\libraries).

This PR replaces the hard coded ref to Documents\Arduino\libraries with a ref to _settings.sketchbookPath that works with the portable version and the installed one.

### CODE REVIEW

**Comment by hellyzh** [comment]
Please check to configure VS Code with Arduino settings for "arduino.path" as below, then the sample will get the correct custom Arduino libraries path. And the hard code one is default folder of downloaded libraries as well as the portable Arduino.
In Visual Studio Code, click File > Preferences > Settings,  then click the Open Settings (JSON) icon in the upper-right corner of the Settings page.
 `"arduino.path": "C:\\Program Files (x86)\\Arduino"`

**Comment by raomin** [comment]
Thanks for your feedback @hellyzh . 

Maybe I didn't explain clearly, the problem is when you are using a portable version of Arduino IDE (regardless whether you use a portable version of VScode or not).

The purpose of installing Arduino as _portable_ is to place it elsewhere than `"C:\Program Files (x86)\Arduino"` ; usually in user writable folder, eg `C;\users\johndoe\arduino-1.8.10`
In this setup, the sketchbook folder is `C;\users\johndoe\arduino-1.8.10\sketchbook` and the downloaded libs are in `C;\users\johndoe\arduino-1.8.10\sketchbook\libraries`
Yet the vscode-arduino plugin adds the standard "c:\user\johndoe\documents\arduino\libraries" which does not exists in this case.

More generally, if you move the sketchbook from the user Documents folder, the custom libraries folder is not included...

This patch points it to {arduino.sketchbook}\libraries which is always where Arduino would put it.

**Comment by raomin** [comment]
Please @dooriya , can you consider this PR? 
I have students with portable version of Arduino and they cannot get their examples working because the custom libraries are not included. As they are beginners it's really not helpful for them.
TIA.

**Comment by hellyzh** [comment]
@raomin, the custom package tools location [code](https://github.com/microsoft/vscode-arduino/blob/c4ed59d7274b49d30830d3fb9b4729e269a58e86/src/arduino/arduino.ts#L671)  should be updated to the same. Could you please also include the change in your PR?

**Comment by hellyzh** [comment]
I suggest to keep it which will not break any other usage. So please do the replace as you mentioned.

**Comment by raomin** [comment]
Done! PR updated.

**Comment by raomin** [comment]
Hi!
Is there still something blocking this PR? 
@dooriya  ?

**Comment by dooriya** [comment]
> Hi!
> Is there still something blocking this PR?
> @dooriya ?

The change looks good to me, approved :)
Sorry for the belated response.

**Comment by elektronikworkshop** [comment]
BTW: All this path fiddling will become obsolete anyways with the automagical `c_cpp_properties.json` configuration I'm currently working on. I have it working here and It's reaching beta for OSX and Linux in the next few days. Windows support will follow.

Progress can be followed here: #438 and especially [here](https://github.com/elektronikworkshop/vscode-arduino/blob/intellisense-autoconfig/BRANCHNOTES.md).

Regards
EW

**Pull request merged**
