### PR TITLE
Correct typo in REAMDE from Ardiuno to Arduino.

### PR DESCRIPTION
**Pull request by CBielstein**
I found and am correcting a typo in README.md from "Ardiuno" to "Arduino"

### CODE REVIEW

**Comment by CBielstein** [comment]
Hi there, maintainers!

Looks like my TravisCI run cancelled after a few hours. I'm doubtful the single line documentation change caused this. :) Please let me know how I can move forward.

Thank you and thanks for your work on this extension!

**Comment by adiazulay** [comment]
We're tracking the TravisCI issue with #1189, and we're also migrating the build system to GitHub Actions.

**Comment by CBielstein** [comment]
That makes sense, thanks!

**Review by adiazulay — APPROVED** [review]
thanks for catching that!

**Pull request merged**
