### PR TITLE
Issue #1268 Fixed pref arguments when using CLI.

### PR DESCRIPTION
**Pull request by Falven**
See Issue #1268

### CODE REVIEW

**Review by adiazulay — APPROVED** [review]
Looks good to me. Will get this in the next build.

**Comment by benmcmorran** [comment]
Sorry, this was unintentionally closed when I removed the old `develop` branch. I'm reopening and retargeting to the newly renamed `main` branch.

**Comment by benmcmorran** [comment]
Thanks for your contribution @Falven!

**Pull request merged**
